// <auto-generated />
using Example;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Example.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Example.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");
 
                    b.Property<string>("City")
                        .HasColumnName("city");

                    b.Property<int?>("EmployeeId")
                        .HasColumnName("employeeid");

                    b.Property<int>("Number")
                        .HasColumnName("number");

                    b.Property<string>("State")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .HasColumnName("street");

                    b.Property<string>("Zipcode")
                        .HasColumnName("zipcode");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("address");
                });

            modelBuilder.Entity("Example.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("department");
                });

            modelBuilder.Entity("Example.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnName("age");

                    b.Property<int?>("DepartmentId")
                        .HasColumnName("departmentid");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("Example.Entities.Address", b =>
                {
                    b.HasOne("Example.Entities.Employee")
                        .WithMany("Addresses")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Example.Entities.Employee", b =>
                {
                    b.HasOne("Example.Entities.Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
